/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CarrierWhereUniqueInput } from "../../carrier/base/CarrierWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DestinationWhereUniqueInput } from "../../destination/base/DestinationWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { PackageModelWhereUniqueInput } from "../../packageModel/base/PackageModelWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { EnumShipmentStatus } from "./EnumShipmentStatus";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class ShipmentWhereInput {
  @ApiProperty({
    required: false,
    type: () => CarrierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CarrierWhereUniqueInput)
  @IsOptional()
  @Field(() => CarrierWhereUniqueInput, {
    nullable: true,
  })
  carrier?: CarrierWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DestinationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DestinationWhereUniqueInput)
  @IsOptional()
  @Field(() => DestinationWhereUniqueInput, {
    nullable: true,
  })
  destination?: DestinationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PackageModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PackageModelWhereUniqueInput)
  @IsOptional()
  @Field(() => PackageModelWhereUniqueInput, {
    nullable: true,
  })
  packageModel?: PackageModelWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  shippingDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumShipmentStatus,
  })
  @IsEnum(EnumShipmentStatus)
  @IsOptional()
  @Field(() => EnumShipmentStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  trackingNumber?: StringNullableFilter;
}

export { ShipmentWhereInput as ShipmentWhereInput };
