/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CarrierWhereUniqueInput } from "../../carrier/base/CarrierWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { DestinationWhereUniqueInput } from "../../destination/base/DestinationWhereUniqueInput";
import { PackageModelWhereUniqueInput } from "../../packageModel/base/PackageModelWhereUniqueInput";
import { EnumShipmentStatus } from "./EnumShipmentStatus";

@InputType()
class ShipmentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CarrierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CarrierWhereUniqueInput)
  @IsOptional()
  @Field(() => CarrierWhereUniqueInput, {
    nullable: true,
  })
  carrier?: CarrierWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DestinationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DestinationWhereUniqueInput)
  @IsOptional()
  @Field(() => DestinationWhereUniqueInput, {
    nullable: true,
  })
  destination?: DestinationWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PackageModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PackageModelWhereUniqueInput)
  @IsOptional()
  @Field(() => PackageModelWhereUniqueInput, {
    nullable: true,
  })
  packageModel?: PackageModelWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  shippingDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumShipmentStatus,
  })
  @IsEnum(EnumShipmentStatus)
  @IsOptional()
  @Field(() => EnumShipmentStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  trackingNumber?: string | null;
}

export { ShipmentUpdateInput as ShipmentUpdateInput };
