/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Shipment } from "./Shipment";
import { ShipmentCountArgs } from "./ShipmentCountArgs";
import { ShipmentFindManyArgs } from "./ShipmentFindManyArgs";
import { ShipmentFindUniqueArgs } from "./ShipmentFindUniqueArgs";
import { CreateShipmentArgs } from "./CreateShipmentArgs";
import { UpdateShipmentArgs } from "./UpdateShipmentArgs";
import { DeleteShipmentArgs } from "./DeleteShipmentArgs";
import { Carrier } from "../../carrier/base/Carrier";
import { Destination } from "../../destination/base/Destination";
import { PackageModel } from "../../packageModel/base/PackageModel";
import { ShipmentService } from "../shipment.service";
@graphql.Resolver(() => Shipment)
export class ShipmentResolverBase {
  constructor(protected readonly service: ShipmentService) {}

  async _shipmentsMeta(
    @graphql.Args() args: ShipmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Shipment])
  async shipments(
    @graphql.Args() args: ShipmentFindManyArgs
  ): Promise<Shipment[]> {
    return this.service.shipments(args);
  }

  @graphql.Query(() => Shipment, { nullable: true })
  async shipment(
    @graphql.Args() args: ShipmentFindUniqueArgs
  ): Promise<Shipment | null> {
    const result = await this.service.shipment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shipment)
  async createShipment(
    @graphql.Args() args: CreateShipmentArgs
  ): Promise<Shipment> {
    return await this.service.createShipment({
      ...args,
      data: {
        ...args.data,

        carrier: args.data.carrier
          ? {
              connect: args.data.carrier,
            }
          : undefined,

        destination: args.data.destination
          ? {
              connect: args.data.destination,
            }
          : undefined,

        packageModel: args.data.packageModel
          ? {
              connect: args.data.packageModel,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Shipment)
  async updateShipment(
    @graphql.Args() args: UpdateShipmentArgs
  ): Promise<Shipment | null> {
    try {
      return await this.service.updateShipment({
        ...args,
        data: {
          ...args.data,

          carrier: args.data.carrier
            ? {
                connect: args.data.carrier,
              }
            : undefined,

          destination: args.data.destination
            ? {
                connect: args.data.destination,
              }
            : undefined,

          packageModel: args.data.packageModel
            ? {
                connect: args.data.packageModel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Shipment)
  async deleteShipment(
    @graphql.Args() args: DeleteShipmentArgs
  ): Promise<Shipment | null> {
    try {
      return await this.service.deleteShipment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Carrier, {
    nullable: true,
    name: "carrier",
  })
  async getCarrier(
    @graphql.Parent() parent: Shipment
  ): Promise<Carrier | null> {
    const result = await this.service.getCarrier(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Destination, {
    nullable: true,
    name: "destination",
  })
  async getDestination(
    @graphql.Parent() parent: Shipment
  ): Promise<Destination | null> {
    const result = await this.service.getDestination(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => PackageModel, {
    nullable: true,
    name: "packageModel",
  })
  async getPackageModel(
    @graphql.Parent() parent: Shipment
  ): Promise<PackageModel | null> {
    const result = await this.service.getPackageModel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
